AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  FunctionName:
    Type: String
    Default: AwsLambdaMinimalExample
    Description: Name of the Lambda function.
  Handler:
    Type: String
    Default: index.handler
    Description: The function within your code that Lambda calls to begin execution.
  Runtime:
    Type: String
    Default: nodejs20.x
    AllowedValues:
      - nodejs16.x
      - nodejs18.x
      - nodejs20.x
    Description: The runtime environment for the Lambda function.
  MemorySize:
    Type: Number
    Default: 1024
    Description: The amount of memory available to the function at runtime.
  S3Bucket:
    Type: String
    Description: The S3 bucket where the Lambda deployment package is stored.
  S3Key:
    Type: String
    Description: The S3 key (file name) for the Lambda deployment package.

Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Ref FunctionName
      Handler: !Ref Handler
      Runtime: !Ref Runtime
      Role: !GetAtt LambdaFunctionRole.Arn
      MemorySize: !Ref MemorySize
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key

  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: AppendToLogsPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
