AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DBInstanceIdentifier:
    Type: String
    Default: MyRDSInstance
    Description: The DB instance identifier.
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.t3.large
    Description: The compute and memory capacity of the DB instance.
  Engine:
    Type: String
    Default: mysql
    AllowedValues:
      - mysql
      - postgres
      - oracle-se2
      - sqlserver-ee
      - sqlserver-se
      - sqlserver-ex
      - sqlserver-web
    Description: The database engine to use.
  EngineVersion:
    Type: String
    Default: "8.0"
    Description: The version number of the database engine to use.
  MasterUsername:
    Type: String
    Default: admin
    Description: The master username for the DB instance.
  MasterUserPassword:
    Type: String
    NoEcho: true
    Description: The master user password for the DB instance.
  AllocatedStorage:
    Type: Number
    Default: 20
    Description: The size of the DB instance storage in gigabytes.
  VPCSecurityGroupIds:
    Type: CommaDelimitedList
    Description: A list of VPC security groups to associate with the DB instance.
  DBSubnetGroupName:
    Type: String
    Description: A DB subnet group to associate with the DB instance.

Resources:
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBInstanceClass: !Ref DBInstanceClass
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      AllocatedStorage: !Ref AllocatedStorage
      VPCSecurityGroups: !Ref VPCSecurityGroupIds
      DBSubnetGroupName: !Ref DBSubnetGroupName
      BackupRetentionPeriod: 7
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2

  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS instance"
      SubnetIds:
        - subnet-xxxxxxxx
        - subnet-yyyyyyyy

Outputs:
  DBInstanceEndpoint:
    Description: The endpoint address of the RDS instance.
    Value: !GetAtt MyDBInstance.Endpoint.Address
  DBInstancePort:
    Description: The port number on which the database accepts connections.
    Value: !GetAtt MyDBInstance.Endpoint.Port
