AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketNamePrefix:
    Type: String
    Description: The prefix for the name of the S3 bucket to create.
  AccessControl:
    Type: String
    Default: Private
    AllowedValues:
      - Private
      - PublicRead
      - PublicReadWrite
      - AuthenticatedRead
      - LogDeliveryWrite
      - BucketOwnerRead
      - BucketOwnerFullControl
    Description: The access control settings for the bucket.
  VersioningConfiguration:
    Type: String
    Default: Suspended
    AllowedValues:
      - Enabled
      - Suspended
    Description: The versioning configuration for the bucket.

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "${BucketNamePrefix}-${AWS::AccountId}"
      AccessControl: !Ref AccessControl
      VersioningConfiguration:
        Status: !Ref VersioningConfiguration

Outputs:
  BucketName:
    Description: The name of the S3 bucket.
    Value: !Ref MyS3Bucket
  BucketArn:
    Description: The ARN of the S3 bucket.
    Value: !GetAtt MyS3Bucket.Arn
  BucketDomainName:
    Description: The domain name of the S3 bucket.
    Value: !GetAtt MyS3Bucket.DomainName
